<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Departamento;

class DepartamentoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departamento =[
            [
                'codigo' => '01',
                'name' => 'Atlántida',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Colón',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Comayagua',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Copán',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Cortés',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Choluteca',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'El Paraíso',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Francisco Morazán',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Gracias a Dios',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Intibucá',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Islas de la Bahía',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'La Paz',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Lempira',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Ocotepeque',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Olancho',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Santa Bárbara',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Valle',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Yoro',
                'pais_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Boaco',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Carazo',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Chinandega',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Chontales',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Estelí',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Granada',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Jinotega',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'León',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Madriz',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Managua',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Masaya',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Matagalpa',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Nueva Segovia',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Río San Juan',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Rivas',
                'pais_id' => 2,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Alabama',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Alaska',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Arizona',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Arkansas',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'California',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Colorado',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Connecticut',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Delaware',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Florida',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Georgia',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Hawaii',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Idaho',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Illinois',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Indiana',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Iowa',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Kansas',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Kentucky',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Louisiana',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Maine',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Maryland',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Massachusetts',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Michigan',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Minnesota',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Mississippi',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Missouri',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '26',
                'name' => 'Montana',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '27',
                'name' => 'Nebraska',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '28',
                'name' => 'Nevada',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '29',
                'name' => 'New Hampshire',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '30',
                'name' => 'New Jersey',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '31',
                'name' => 'New Mexico',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '32',
                'name' => 'New York',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '33',
                'name' => 'North Carolina',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '34',
                'name' => 'North Dakota',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '35',
                'name' => 'Ohio',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '36',
                'name' => 'Oklahoma',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '37',
                'name' => 'Oregon',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '38',
                'name' => 'Pennsylvania',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '39',
                'name' => 'Rhode Island',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '40',
                'name' => 'South Carolina',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '41',
                'name' => 'South Dakota',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '42',
                'name' => 'Tennessee',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '43',
                'name' => 'Texas',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '44',
                'name' => 'Utah',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '45',
                'name' => 'Vermont',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '46',
                'name' => 'Virginia',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '47',
                'name' => 'Washington',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '48',
                'name' => 'West Virginia',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '49',
                'name' => 'Wisconsin',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '50',
                'name' => 'Wyoming',
                'pais_id' => 3,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Aguascalientes',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Baja California',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Baja California Sur',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Campeche',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Coahuila',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Colima',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Chiapas',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Chihuahua',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Ciudad de México',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Durango',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Guanajuato',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Guerrero',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Hidalgo',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Jalisco',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'México',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Michoacán',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Morelos',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Nayarit',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Nuevo León',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Oaxaca',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Puebla',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Querétaro',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Quintana Roo',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'San Luis Potosí',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Sinaloa',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '26',
                'name' => 'Sonora',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '27',
                'name' => 'Tabasco',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '28',
                'name' => 'Tamaulipas',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '29',
                'name' => 'Tlaxcala',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '30',
                'name' => 'Veracruz',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '31',
                'name' => 'Yucatán',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '32',
                'name' => 'Zacatecas',
                'pais_id' => 4,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Belize',
                'pais_id' => 5,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Cayo',
                'pais_id' => 5,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Corozal',
                'pais_id' => 5,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Orange Walk',
                'pais_id' => 5,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Stann Creek',
                'pais_id' => 5,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Toledo',
                'pais_id' => 5,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Alta Verapaz',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Baja Verapaz',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Chimaltenango',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Chiquimula',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Petén',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'El Progreso',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Quiché',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Escuintla',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Guatemala',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Huehuetenango',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Izabal',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Jalapa',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Jutiapa',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Quetzaltenango',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Retalhuleu',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Sacatepéquez',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'San Marcos',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Santa Rosa',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Sololá',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Suchitepéquez',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Totonicapán',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Zacapa',
                'pais_id' => 6,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Ahuachapán',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Cabañas',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Chalatenango',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Cuscatlán',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'La Libertad',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'La Paz',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'La Unión',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Morazán',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'San Miguel',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'San Salvador',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'San Vicente',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Santa Ana',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Sonsonate',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Usulután',
                'pais_id' => 7,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'San José',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Alajuela',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Cartago',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Heredia',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Guanacaste',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Puntarenas',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Limón',
                'pais_id' => 8,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Bocas del Toro',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Coclé',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Colón',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Chiriquí',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Darién',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Herrera',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Los Santos',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Panamá',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Veraguas',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Panamá Oeste',
                'pais_id' => 9,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Artibonite',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Centre',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Grand\'Anse',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Nord',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Nord-Est',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Nord-Ouest',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Ouest',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Sud',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Sud-Est',
                'pais_id' => 10,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Amazonas',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Áncash',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Apurímac',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Arequipa',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Ayacucho',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Cajamarca',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Callao',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Cusco',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Huancavelica',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Huánuco',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Ica',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Junín',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'La Libertad',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Lambayeque',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Lima',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Loreto',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Madre de Dios',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Moquegua',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Pasco',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Piura',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Puno',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'San Martín',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Tacna',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Tumbes',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Ucayali',
                'pais_id' => 11,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Pinar del Río',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'La Habana',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Ciudad de La Habana',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Matanzas',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Villa Clara',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Cienfuegos',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Sancti Spíritus',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Ciego de Ávila',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Camagüey',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Las Tunas',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Holguín',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Granma',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Santiago de Cuba',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Guantánamo',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Isla de la Juventud',
                'pais_id' => 12,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Buenos Aires',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Catamarca',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Chaco',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Chubut',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Córdoba',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Corrientes',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Entre Ríos',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Formosa',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Jujuy',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'La Pampa',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'La Rioja',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Mendoza',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Misiones',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Neuquén',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Río Negro',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Salta',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'San Juan',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'San Luis',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Santa Cruz',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Santa Fe',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Santiago del Estero',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Tierra del Fuego',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Tucumán',
                'pais_id' => 13,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Acre',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Alagoas',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Amapá',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Amazonas',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Bahía',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Ceará',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Distrito Federal',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Espírito Santo',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Goiás',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Maranhão',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Mato Grosso',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Mato Grosso do Sul',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Minas Gerais',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Pará',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Paraíba',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Paraná',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Pernambuco',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Piauí',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Rio de Janeiro',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Rio Grande do Norte',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Rio Grande do Sul',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Rondônia',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Roraima',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Santa Catarina',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '26',
                'name' => 'São Paulo',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '27',
                'name' => 'Sergipe',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '28',
                'name' => 'Tocantins',
                'pais_id' => 14,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Arica y Parinacota',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Tarapacá',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Antofagasta',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Atacama',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Coquimbo',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Valparaíso',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Región Metropolitana de Santiago',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Libertador General Bernardo O\'Higgins',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Maule',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Ñuble',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Biobío',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'La Araucanía',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Los Ríos',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Los Lagos',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Aysén del General Carlos Ibáñez del Campo',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Magallanes y de la Antártica Chilena',
                'pais_id' => 15,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Bogotá D.C.',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Atlántico',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Antioquia',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Amazonas',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Arauca',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Archipiélago de San Andrés,',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Caldas',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Caquetá',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Casanare',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Cauca',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Cesar',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Chocó',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Córdoba',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Cundinamarca',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Guainía',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Guaviare',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Huila',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'La Guajira',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Magdalena',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Meta',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Nariño',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Norte de Santander',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Putumayo',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Quindío',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Risaralda',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Santander',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '26',
                'name' => 'Sucre',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '27',
                'name' => 'Tolima',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '28',
                'name' => 'Valle del Cauca',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '29',
                'name' => 'Vaupés',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '30',
                'name' => 'Vichada',
                'pais_id' => 16,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Amazonas',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Anzoátegui',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Apure',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Aragua',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Barinas',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Bolívar',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Carabobo',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Cojedes',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Delta Amacuro',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Falcón',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Guárico',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Lara',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Mérida',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Miranda',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Monagas',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Nueva Esparta',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Portuguesa',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Sucre',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Táchira',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Trujillo',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Vargas',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Yaracuy',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Zulia',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Distrito Capital',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Dependencias Federales',
                'pais_id' => 17,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Chuquisaca',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'La Paz',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Cochabamba',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Oruro',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Potosí',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Tarija',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Santa Cruz',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Beni',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Pando',
                'pais_id' => 18,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Barima-Waini',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Cuyuni-Mazaruni',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Demerara-Mahaica',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'East Berbice-Corentyne',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Essequibo Islands-West Demerara',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Mahaica-Berbice',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Pomeroon-Supenaam',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Potaro-Siparuni',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Upper Demerara-Berbice',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Upper Takutu-Upper Essequibo',
                'pais_id' => 19,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Azuay',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Bolívar',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Cañar',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Carchi',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Chimborazo',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Cotopaxi',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'El Oro',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Esmeraldas',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Galápagos',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Guayas',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Imbabura',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Loja',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Los Ríos',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Manabí',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Morona Santiago',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Napo',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Orellana',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Pastaza',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Pichincha',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Santa Elena',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Santo Domingo de los Tsáchilas',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Sucumbíos',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Tungurahua',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Zamora Chinchipe',
                'pais_id' => 20,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Guayana Francesa',
                'pais_id' => 21,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Concepción',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'San Pedro',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Cordillera',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Guairá',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Caaguazú',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Caazapá',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Itapúa',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Misiones',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Paraguarí',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Alto Paraná',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Central',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Ñeembucú',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Amambay',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Canindeyú',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Presidente Hayes',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Alto Paraguay',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Boquerón',
                'pais_id' => 22,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Martinica',
                'pais_id' => 23,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Suriman',
                'pais_id' => 24,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Artigas',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Canelones',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Cerro Largo',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Colonia',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Durazno',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Flores',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Florida',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Lavalleja',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Maldonado',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Montevideo',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Paysandú',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Río Negro',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Rivera',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Rocha',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Salto',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '16',
                'name' => 'San José',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Soriano',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Tacuarembó',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Treinta y Tres',
                'pais_id' => 25,
                'created_by' => 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Caribe Neerlandés',
                'pais_id' => 26,
                'created_by' => 1,
            ],
            ];
            foreach ($departamento as $depto) {
                Departamento::forceCreate($depto);
            }
    }
}
