<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $municipios =[
            [
                'codigo' => '01',
                'name' => 'La Ceiba',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'El Porvenir',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Esparta',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Jutiapa',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'La Masica',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'San Francisco',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Tela',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Arizona',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Iriona',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Santa Fé',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Brus Laguna',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Juan Francisco Bulnes',
                'departamento_id' => 1,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Trujillo',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Balfate',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Iriona',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Limón',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Sabá',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Santa Fe',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Santa Rosa de Aguán',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Sonaguera',
                'departamento_id' => 2,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Comayagua',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Ajuterique',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'El Rosario',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Esquías',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Humuya',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'La Libertad',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Lamaní',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'La Trinidad',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Lejamaní',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Meámbar',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Minas de Oro',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Ojos de Agua',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'San Jerónimo',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'San José de Comayagua',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'San José del Potrero',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'San Luis',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'San Sebastián',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Siguatepeque',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Taulabé',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Villa de San Antonio',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Las Lajas',
                'departamento_id' => 3,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Santa Rosa de Copán',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Cabañas',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Concepción',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Copán Ruinas',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Corquín',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Cucuyagua',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Dolores',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Dulce Nombre',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'El Paraíso',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Florida',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'La Jigua',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'La Unión',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Nueva Arcadia',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'San Agustín',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'San Antonio',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'San Jerónimo',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'San José',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'San Juan de Opoa',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'San Nicolás',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'San Pedro',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Santa Rita',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Trinidad de Copán',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Veracruz',
                'departamento_id' => 4,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'San Pedro Sula',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Choloma',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Omoa',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Pimienta',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Potrerillos',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Puerto Cortés',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'San Antonio de Cortés',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'San Francisco de Yojoa',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'San Manuel',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Santa Cruz de Yojoa',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Villanueva',
                'departamento_id' => 5,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Choluteca',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Apacilagua',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Namasigüe',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'San Antonio de Flores',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Duyure',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'San Isidro',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Pespire',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'San José',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'San Marcos de Colón',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Santa Ana de Yusguare',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Orocuina',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Marcovia',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Morolica',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'El Corpus',
                'departamento_id' => 6,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Yuscarán',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Alauca',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Danlí',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'El Paraíso',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Guinope',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Jacaleapa',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Liure',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Morocelí',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Oropoli',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Potrerillos',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'San Antonio de Flores',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'San Lucas',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'San Matías',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Soledad',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Teupasenti',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Texiguat',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Vado Ancho',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Yauyupe',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Trojes',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Sabanagrande',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Guayape',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Las Lajas',
                'departamento_id' => 7,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Distrito Central',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Talanga',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Guaimaca',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Valle de Ángeles',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Santa Lucía',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Maraita',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'San Antonio de Oriente',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Cedros',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Ojojona',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Reitoca',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'La Venta',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'San Buenaventura',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'San Juan de Flores',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Santa Ana',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Villa de San Francisco',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Vallecillo',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Cantarranas',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'La Libertad',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'San José de la Vega',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'San Miguelito',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Tatumbla',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Santa Ana',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '23',
                'name' => 'San Pedro de los Rosales',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '24',
                'name' => 'La Paz',
                'departamento_id' => 8,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Puerto Lempira',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Brus Laguna',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Ahuas',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Juan Francisco Bulnes',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Ramón Villeda Morales',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Wampusirpe',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Puerto Patuca',
                'departamento_id' => 9,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'La Esperanza',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Camasca',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Colomoncagua',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Concepción',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Dolores',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Intibucá',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Jesus de Otoro',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Magdalena',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Masaguara',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'San Antonio',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'San Isidro',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'San Juan',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'San Marcos de Sierra',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'San Miguel Guancapla',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Santa Lucía',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Yamaranguila',
                'departamento_id' => 10,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Roatán',
                'departamento_id' => 11,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Guanaja',
                'departamento_id' => 11,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Utila',
                'departamento_id' => 11,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'La Paz',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Aguanqueterique',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Cabañas',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Cane',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Chinacla',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Guajiquiro',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Lauterique',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Marcala',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Mercedes de Oriente',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Opatoro',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'San Antonio del Norte',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'San José',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'San Juan',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'San Pedro de Tutule',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Santa Ana',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Santa Elena',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Santa María',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'Santiago de Puringla',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'Yarula',
                'departamento_id' => 12,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Gracias',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Belén',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Candelaria',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Cololaca',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Erandique',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Gualcince',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Guarita',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'La Campa',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'La Iguala',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Las Flores',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'La Unión',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'La Virtud',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Lepaera',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Mapulaca',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Piraera',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'San Andrés',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'San Francisco',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'San Juan Guarita',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'San Manuel Colohete',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'San Rafael',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'San Sebastián',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Santa Cruz',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Talgua',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '24',
                'name' => 'Tambla',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Tomalá',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '26',
                'name' => 'Valladolid',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '27',
                'name' => 'Virginia',
                'departamento_id' => 13,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Nueva Ocotepeque',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Belén Gualcho',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Concepción',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Dolores Merendon',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Fraternidad',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'La Encarnación',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'La Labor',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Lucerna',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Merendón',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'San Fernando',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'San Francisco del Valle',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'San Jorge',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'San Marcos',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Santa Fé',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Sensenti',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Sinuapa',
                'departamento_id' => 14,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Juticalpa',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Campamento',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Catacamas',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Concordia',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Dulce Nombre de Culmí',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'El Rosario',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Esquipulas del Norte',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Gualaco',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Guarizama',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Guata',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Guayape',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Jano',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'La Unión',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Mangulile',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Manto',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Salamá',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'San Esteban',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'San Francisco de Becerra',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'San Francisco de la Paz',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'Santa María del Real',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'Silca',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '22',
                'name' => 'Yocón',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '23',
                'name' => 'Patuca',
                'departamento_id' => 15,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Santa Bárbara',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Arada',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Atima',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Azacualpa',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Ceguaca',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Concepción del Norte',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Concepción del Sur',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Chinda',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'El Nispero',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Gualala',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '11',
                'name' => 'Ilama',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '12',
                'name' => 'Macuelizo',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '13',
                'name' => 'Naranjito',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '14',
                'name' => 'Nuevo Celilac',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '15',
                'name' => 'Petoa',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '16',
                'name' => 'Protección',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '17',
                'name' => 'Quimistán',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '18',
                'name' => 'San Francisco de Ojuera',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '19',
                'name' => 'San José de Colinas',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '20',
                'name' => 'San Luis',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '21',
                'name' => 'San Marcos',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '22',
                'name' => 'San Nicolás',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '23',
                'name' => 'San Pedro Zacapa',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '24',
                'name' => 'San Vicente Centenario',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '25',
                'name' => 'Santa Rita',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '26',
                'name' => 'Trinidad',
                'departamento_id' => 16,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Nacaome',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Alianza',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'Amapala',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'Aramecina',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Caridad',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Goascorán',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Langue',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'San Francisco de Coray',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'San Lorenzo',
                'departamento_id' => 17,
                'created_by'=> 1,
            ],
            [
                'codigo' => '01',
                'name' => 'Yoro',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '02',
                'name' => 'Arenal',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '03',
                'name' => 'El Negrito',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '04',
                'name' => 'El Progreso',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '05',
                'name' => 'Jocón',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '06',
                'name' => 'Morazán',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '07',
                'name' => 'Olanchito',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '08',
                'name' => 'Santa Rita',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '09',
                'name' => 'Sulaco',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            [
                'codigo' => '10',
                'name' => 'Victoria',
                'departamento_id' => 18,
                'created_by'=> 1,
            ],
            ];
            foreach ($municipios as $municipio) {
                Municipio::forceCreate($municipio);
            }
    }
}
