<?php

namespace Database\Seeders;

use App\Models\Servicio;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ServicioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $servicios=[
            [
                'nombre_servicio'=>'Manejo de recibos sólidos',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP1',
                'importes'=>900,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Bomberos',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP2',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Alumbrado Público',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP3',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Medio Ambiente',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP4',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Seguridad Ciudadana',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP5',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Mercado Público y Centros Comerciales',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP6',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Cementereos Públicos',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP7',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Uso de vias públicas',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP8',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Facilidad para destace de ganado y similares',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP9',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Estacionamiento y Parquimetro',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP10',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Circulacion y mantenimiento vial',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP11',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Agua',
                'tipo_servicio_id'=>1,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP12',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Autorizacion libros contables',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP13',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Extensión de permisos de operación de negocios y licencias',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP14',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Autorización y permisos para espectáculos públicos',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP15',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Permisos de explotación',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP16',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Matricula de vehículo, armas de juego, de agricultores, y otros',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP17',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Permisos de percusiones y demolición de edificios',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP18',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Elaboración de levantamiento topográficos y lotificaciones',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP19',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Elaboración de planos y diseños de elementos constructivos',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP20',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Extensión de certificaciones constancias',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP21',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Tramitaciones y celebración de matrimonio civiles',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP22',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Limieza de solares',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP23',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Atención en emergencia por desastres naturales',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP24',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],
            [
                'nombre_servicio'=>'Extensión de licencias operación para el ejercicio profesional',
                'tipo_servicio_id'=>2,
                'nivel_servicio_id'=>1,
                'clave_presupuestaria'=>'CP25',
                'importes'=>1000.00,
                'fecha_creacion'=>'2024-03-09',
                'status'=>'1',
                'created_by'=>1,
            ],



        ];

        foreach ($servicios as $ser) {
            Servicio::forceCreate($ser);
        }
    }


}
